## File defining how to connect to nomad
# secrets are passed through the environment

variable "nomad_server_url" {
  type        = string
  sensitive   = false
  description = "Nomad server address allowing to administer the cluster jobs."
  default     = "https://moleson.cscs.ch:4646"
}

variable "nomad_secret_id" {
  type        = string
  sensitive   = true
  description = "Nomad HEX SecredID to access the server."
}

variable "nomad_ca_cert" {
  type        = string
  sensitive   = true
  description = "Nomad CA certificate generated by the server (.pem)."
  default     = "certs/nomad-agent-ca.pem"
}

variable "nomad_cli_cert" {
  type        = string
  sensitive   = true
  description = "Nomad CLI certificate generated by the server (.pem)."
  default     = "certs/global-cli-nomad.pem"
}

variable "nomad_cli_key" {
  type        = string
  sensitive   = true
  description = "Nomad CLI key generated by the server (.pem)."
  default     = "certs/global-cli-nomad-key.pem"
}

provider "nomad" {
  address   = var.nomad_server_url
  secret_id = var.nomad_secret_id
  ca_file   = var.nomad_ca_cert
  cert_file = var.nomad_cli_cert
  key_file  = var.nomad_cli_key
}

